### ISSUE TITLE
About Retrieval_Methods code

### ISSUE THREAD

**Issue by Peanut736** [Eduard6421/iQPP#1]
Hi, thanks for your code first. And do you change the code on Radenovic-et-al and Revaud-et-al code?

**Comment by Eduard6421** [comment]
Greetings @Peanut736!
The code on Radenovic-et-Al and Revaud-et-al is included in the repository as sub-repositories. The code is indeed modify in order to obtain the desired values ( printing ap for each image / printing p@k for each image);
Please do message further if you need any help with your setup!
